### ISSUE TITLE
Add JavaScript Style Guide + Linter

### ISSUE THREAD

**Issue by prosauer** [ReTtiChDieOrganisation/ReTtiChDasRepo#96]
**Is your feature request related to a problem? Please describe.**
We don't have checks in place to ensure merge requests are formatted correctly

**Describe the solution you'd like**
There is a solution available called [standard](https://github.com/standard/standard) and we should add this as a pre-commit hook

**Describe alternatives you've considered**
There might be other solutions or one could gather and enforce style rules 

Add Todos
- [ ] Install standard locally
- [ ] Test its functionality
- [ ] Implement it locally as pre-commit hook
- [ ] Add it to github actions

**Don't forget to assign at least one Developer who you think might work on this**

**Additional context**
This might do the trick in our pipeline?
```
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: master
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
```
